config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :pins do
    resources :comments

   member do
      post '/like' => 'pins#like'
    end
  end

  get '/:username' => 'users#show', as: 'user'

  devise_for :users
  root 'pins#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	 belongs_to :user
  	 belongs_to :pin
 	 validates_uniqueness_of :pin_id, scope: :user_id
  	 validates_presence_of :pin_id
  	 validates_presence_of :user_id
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates_presence_of :description
	belongs_to :user
	belongs_to :board
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
	validates_presence_of :description, :image, :board_id
	has_attached_file :pin_image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :pin_image, content_type: /\Aimage\/.*\Z/



end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_pins, through: :likes, source: :pin

  validates_uniqueness_of :username

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pins_path, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @like = @pin.likes.build(user_id: current_user.id)
    if @like.save
      flash[:notice] =  "You liked a recording from #{@pin.user.username}!"
      redirect_to(pins_path)
    else
      flash[:notice] =  "You have already liked this recording!"
      redirect_to(pins_path)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
   def pin_params
    params.require(:pin).permit(:title, :description, :pin_image)
   end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.image.attach(params[:post][:image])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:tittle, :content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	   @user = User.find_by username: params[:username]
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cosmic Code</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <!-- masonry -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.js"></script>
    <!-- or -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
    <script src="/path/to/masonry.pkgd.min.js"></script>

    <!-- ImagesLoaded -->
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <!-- or -->
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.js"></script>

    <style type="text/css"> </style>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

<<nav class="navbar navbar-fixed-top navbar-custom">
  <a class  = "navbar-brand" href="">
    <img src="https://tchol.org/images/wjsn-logo-png-1.png" height="35" width="40" alt="Logo">
   </a>
      <div class="container">
        <div class="navbar-header"> 
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>  

        
          <%= link_to "Cosmic Code", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class= "active"><%= link_to "Inicio", root_path%></li>
            <li> <%= link_to 'Pins', pins_path %> </li>
            
          </ul>
           <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
               <li><%= link_to 'Nuevo Pin', new_pin_path %></li>
               <li><%= link_to 'Edita tu perfil', edit_user_registration_path %> </li>
               <li><%= link_to 'Cerrar Sección', destroy_user_session_path, method: :delete %></li>
            <% else %>
               <li><%= link_to 'Ingresar', new_user_session_path %> </li>
               <li><%= link_to 'Registrar', new_user_registration_path %></li>
           <% end -%>
          </ul>
        </div><!--/.cierre del navbar -->
      </div>
    </nav>

<div class = "container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>

  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |form| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :pin_image %><br>
    <%= form.file_field :pin_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Mostrar', @pin %> |
<%= link_to 'Regresar', pins_path %>

app/views/pins/index.html.erb
<div class="gallery-container">
  <% @pins.each do |pin| %>

        <div class = "col-md-4 pin-item">
        <div class="panel panel-default pin">
          <div class="panel-body">
              <%= link_to (image_tag pin.pin_image.url(:medium)), pin %> 
          </div>
            <div class="panel-footer">
               <p><strong><%= link_to pin.user.username, user_path(pin.user.username) %></strong></p>
              <p> <%= pin.description %></p>
              <p><%= pluralize(pin.likes.count, "like")%></p>

              <% if pin.user == current_user %>

              <div> 
                <%= link_to 'Editar', edit_pin_path(pin) %> |
                <%= link_to 'ELiminar', pin, method: :delete, data: { confirm: 'Estas seguro?' } %>
                <%= link_to 'Like', like_pin_path(pin), method: :post, class: 'pul-right' %>
              </div>
            <% end %>
          </div>
       </div>
     </div>
   <% end %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <%= @pin.description %>
</p>

<div>
	<%= image_tag @pin.pin_image.url (:medium) %>
</div>

<%= link_to 'Editar', edit_pin_path(@pin) %> |
<%= link_to 'Regresar', pins_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= form.label :image %>
   <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Tittlecontect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.tittlecontect %></td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'ELiminar', post, method: :delete, data: { confirm: 'Esta seguro' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Pin', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<% if @post.image.attached? %>
 	<p>
 		<strong>Image:</strong>
 	<br>
		<%= image_tag @post.image.variant(resize: "100x100") %>
<% end %>

<p>
  <strong>Tittlecontect:</strong>
  <%= @post.tittlecontect %>
</p>


<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Regresar', posts_path %>

app/views/users/show.html.erb
<div>
  <%= image_tag @user.avatar.url(:thumb) %>
</div>

<h3> <%= @user.username %></h3>

<div class = "row cosmic girl-grid">
  <% @user.pins.each do |pin| %>
    <div class = "col-md-4 pin-item">
        <div class="panel panel-default pin">
          <div class="panel-body">
              <%= link_to image_tag(pin.pin_image.url(:medium)), pin %>
          </div>
            <div class="panel-footer">
              <p><strong><%= link_to pin.user.username, user_path(pin.user.username) %></strong></p>
              <p> <%= pin.description %></p>
              <% if pin.user == current_user %>

              <div> 
                <%= link_to 'Editar', edit_pin_path(pin) %> |
                <%= link_to 'Eliminar', pin, method: :delete, data: { confirm: 'Esta seguro?' } %>
              </div>
            <% end %>
          </div>
       </div>
     </div>
   <% end %>
</div>

<% if can? :create, Pin %>
  <%= link_to 'Nuevo Pin', new_pin_path, class:"btn btn-primary" %>
<% end %>